### ISSUE TITLE
Non standard Mvn repository layout

### ISSUE THREAD

**Issue by r1m** [fmidev/fmi-os-mvn-repo#1]
Can you fix the layout so that this repository can be added as a repository in Jfrog Artifactory ?

**Comment by ilkkarinne** [comment]
Hi @r1m, can you be more specific on the issue you are having with using this repository with jfrog?
We are using this repo in our Maven 2 builds without issues, the maven repository configuration is shown at https://github.com/fmidev/fmi-os-parent-pom

Perhaps you are trying to use the Github UI URLs (https://github.com/fmidev/fmi-os-mvn-repo/blob/master/fi/fmi/avi/converter/fmi-avi-messageconverter/4.0.2/fmi-avi-messageconverter-4.0.2.pom) instead of "raw" URLs (https://raw.githubusercontent.com/fmidev/fmi-os-mvn-repo/master/fi/fmi/avi/converter/fmi-avi-messageconverter/4.0.2/fmi-avi-messageconverter-4.0.2.pom)?

**Comment by r1m** [comment]
Hi @ilkkarinne,
I was referring to the fact the repository as hosted on github is missing index files that prevent JFrog Artifactory to scan it.
However, even if the mirroring setup shows an error. We can still mirror it perfectly by ignoring the error.

I opened this ticket before we figured it out.
We can close it.
